### ISSUE TITLE
Add a license to rbt.el

### ISSUE THREAD

**Issue by JorisE** [joeheyming/rbt.el#1]
I'd like to check out if I can work on this and maybe add it to Melpa if I can make it work for me. Would you consider adding a license?

Most emacs extensions have a statement including the GPL like this: https://github.com/magnars/dash.el/blob/master/dash.el

**Comment by joeheyming** [comment]
done!

Strange, I thought I committed this to melpa :-p

https://melpa.org/#/rbt

**Comment by joeheyming** [comment]
I'm curious to know what issues you are having

The way I use this module is I look at git logs with magit,

then I call rbt-review-commit when my cursor is over a git commit id

This pops up a menu that asks if I want to edit an existing review or add a new one.

I would like to have better integration with magit.  That way you could submit a review without having to go to the magit git log page.

**Comment by JorisE** [comment]
It not being on Melpa was my most pressing problem :) Tnx! I have not run into any other problems thus far.
